cache_dir: data
listen: ":41234"
repos:
  archlinux/$repo/os/$arch:
    impl: pacman
    upstreams:
      - https://ftp.halifax.rwth-aachen.de/archlinux/$repo/os/$arch
    args:
      reponame: $repo
  alpine/$version/$repo/$arch:
    impl: apk
    upstreams: [https://dl-cdn.alpinelinux.org/alpine/$version/$repo/$arch]
