cache_dir: data
listen: ":41234"
repos:
  archlinux/$repo/os/x86_64:
    impl: pacman
    upstreams:
      - https://ftp.halifax.rwth-aachen.de/archlinux/$repo/os/x86_64
    args:
      reponame: $repo
  archlinux/$repo/os/armv7h:
    impl: pacman
    upstreams:
      - http://mirror.archlinuxarm.org/armv7h/$repo
    args:
      reponame: $repo
  archlinux/$repo/os/aarch64:
    impl: pacman
    upstreams:
      - http://mirror.archlinuxarm.org/aarch64/$repo
    args:
      reponame: $repo
  alpine/$version/$repo/$arch:
    impl: apk
    upstreams: [https://dl-cdn.alpinelinux.org/alpine/$version/$repo/$arch]
