#!/bin/bash
if [ $# -ne 1 ]; then
	echo "Usage: $0 <server-url>"
	echo ""
	echo "Will request all packages from the pacman-smartmirror instance at <server-url> so"
	echo "the smartmirror downloads them and will update them in the future"
	echo ""
	echo "Example: $0 http://localhost:41234"
	exit 1
fi

printf -v installed '[%s]' "$(gettext installed)"
SERVER=$1
echo "Requesting all locally installed repos from: $SERVER_URL"
ARCH=$(uname -m)
pacman -Sl | awk -v i="$installed" '$NF == i { print $1,$2,$3 }' | while read -r line
do
	pkg=($line)
	REPO=${pkg[0]}
	NAME=${pkg[1]}
	VERSION=${pkg[2]}
	PKGARCH=any
	if [[ $(pacman -Qi $NAME | grep $ARCH) ]]; then
		PKGARCH=$ARCH
	fi
	RPATH=$REPO/os/$ARCH/$NAME-$VERSION-$PKGARCH.pkg.tar.xz
	echo "Requesting $RPATH"
	curl -I "$SERVER/$RPATH?bg" &> /dev/null
done
